---
title: "Welcome to Global Business Services Today"
subtitle: A showcase for data science in action
sidebar: false
page-layout: article
toc: false
title-block-banner: true
---
Welcome to the home of **Global Business Services Today**, a project by the [Dr. Han-Teng Liao](http://hanteng.sapiens.cv/). This site and its content are being developed and curated to help you deliver timely, quality, impactful AI-driven people-centered innovations in global business services. We connect the dots, meeting the complexity of global value chians and business services.

<!-- [Meet the team](global-pulse/editors-blog/posts/2022/10/18/meet-the-team.qmd) -->

## What are our aims?
As the field of data science evolves rapidly - with new tools, controversies, and breakthroughs emerging almost daily - Global Business Services Today offers a space for timely, thoughtful responses grounded in the expertise of our contributors and reviewed by a distinguished editorial board.
We want to serve people working in data science who are looking for practical insights, methodological rigour and thought-leadership that informs their work and decision-making.
We want to help you: 
  
* discover and learn more efficiently;  
* acquire practical problem-solving skills;  
* share your knowledge and accomplishments publicly;  
* work smarter, ethically, and more effectively.  

## What we provide
Commentary, case studies, interviews, and explainers that speak directly to latest events and emerging trends. 
Whether unpacking the implications of a new technological development or product launch, or spotlighting innovative practice in the field, the platform is practical, credible and unafraid to ask the hard questions.

## How you can get involved
See our open [call for contributions](global-pulse/editors-blog/posts/2025/07/08/relaunch-CFS.qmd).